version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Europe/London
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - "form3tech/scaling-codeowners"
