version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - nicholasham
  - andykuszyk
  - markhowardform3
  - martinreus-form3
