version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - cyclop
    - dupl
    - err113
    - funlen
    - gocognit
    - gocyclo
    - godot
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - varnamelen
    - wsl
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Please use go built-in error wrapping and handling via `fmt` and `errors` packages
            - pkg: github.com/giantswarm/retry-go
              desc: Please use https://github.com/avast/retry-go/v4
    exhaustruct:
      include:
        - github.com/form3tech-oss/f1/v2/internal/run/views.*
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: kebab
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: \.go
        text: 'SA1019: (.*.Logger|testing.WithLogrusLogger)'
      - linters:
          - dupword
          - lll
          - unparam
          - wrapcheck
        path: _test\.go
      - linters:
          - staticcheck
        path: _test\.go
        text: ST1003
      - linters:
          - revive
        path: _test\.go
        text: 'var-naming: don''t use underscores in Go names;'
    paths:
      - vendor$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/form3tech-oss/f1)
  exclusions:
    generated: lax
    paths:
      - vendor$
      - third_party$
      - builtin$
      - examples$
