language: go
git:
  depth: false
go:
- "1.19"
services: docker
before_script:
- export PATH=$PATH:$HOME/.local/bin:$GOPATH/bin
- export REPO=$TRAVIS_REPO_SLUG
if: tag IS blank
jobs:
  include:
  - stage: test
    name: Run Tests
    script:
    - make install-goimports
    - make test
